import React from 'react';
import './style.css';

const Band = () => {
  return (
    <div className="band">
      <div className="band1 container">
        <h1>THE BAND</h1>
        <div>
          <p>
            1974, IN THE VERY DEPTH OF EUROPE, FOUR INDIVIDUALS DISCOVERED THE
            ROAR THAT PRODUCED A SUCCESSION OF TRANSISTORS AND TUBES ONCE
            CONNECTED TO A MAGICAL INSTRUMENT… IT WAS LOUD, SENSUAL AND CHAOTIC.
            IN EXCESS FOR SURE. THEY DISAPPEARED IN THE MOST BIZARRE
            CIRCUMSTANCES AND NOBODY EVERY HEARD OF THEM SINCE THEN. IN 2009, A
            GROUP OF THE SAME NUMBER OF INDIVIDUALS CLAIMS IT ESCAPED FROM A
            DARK AND SECRET CRYONICS PROJECT. AWAKENED IN IVRY SUR SEINE,
            FRANCE, THEY INTEND TO CONTINUE THE STORY WHERE IT WAS STOPPED. THIS
            DECLARATION, IF NOT A VENGEANCE, WRECK PLUS DELIVERS IT IN AN OLD
            SCHOOL HEAVY METAL FASHION, THROUGH INNOVATIVE SONGS WHERE THE RIFF
            IS KING. EVERY SONG HAS AN IDENTIFY OF ITS OWN AND A MEMORABLE
            ATMOSPHERE. ALL TOGETHER THIS FORMS A TRIBUTE TO BLACK SABBATH,
            JUDAS PRIEST, KISS, ZZ TOP AND BLUE OŸSTER CULT…
          </p>
        </div>
      </div>
    </div>
  );
};

export default Band;
